const LAND_PETS = [
  {
    id: "elizardotchi",
    name: "蜥蜴吉",
    member: "Tamagotchi Land",
    animalType: "land mascot",
    personality: ["curious", "warm", "quick", "sunny"],
    favoriteItem: "warm stone",
    favoriteFood: "tiny fruit",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["蜥蜴吉正在晒太阳。", "今天也要慢慢变精神。"],
    voiceLine: "sunny-lizard",
    theme: { primary: "#f3f7df", secondary: "#9fc45b", accent: "#3c4f1d" },
    ready: true
  },
  {
    id: "furawatchi",
    name: "芙朵吉",
    member: "Tamagotchi Land",
    animalType: "flower mascot",
    personality: ["gentle", "bright", "dreamy", "kind"],
    favoriteItem: "flower charm",
    favoriteFood: "berry cake",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["芙朵吉开花啦。", "给你一点花香好运。"],
    voiceLine: "flower-bloom",
    theme: { primary: "#fff0f7", secondary: "#ef91bd", accent: "#6b2949" },
    ready: true
  },
  {
    id: "gumax",
    name: "叉叉熊",
    member: "Tamagotchi Land",
    animalType: "bear mascot",
    personality: ["soft", "bold", "loyal", "sleepy"],
    favoriteItem: "tiny cushion",
    favoriteFood: "honey toast",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["叉叉熊想抱抱。", "今天也很努力地发呆。"],
    voiceLine: "bear-hug",
    theme: { primary: "#f6efe5", secondary: "#c99b63", accent: "#5c3b1e" },
    ready: true
  },
  {
    id: "hebitchi",
    name: "蛇蛇吉",
    member: "Tamagotchi Land",
    animalType: "snake mascot",
    personality: ["clever", "calm", "slick", "playful"],
    favoriteItem: "round pebble",
    favoriteFood: "melon cube",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["蛇蛇吉悄悄路过。", "嘶嘶，发现新路线。"],
    voiceLine: "snake-path",
    theme: { primary: "#eaf7ec", secondary: "#74be83", accent: "#1e5a32" },
    ready: true
  },
  {
    id: "mametchi",
    name: "麻美吉",
    member: "Tamagotchi Land",
    animalType: "classic mascot",
    personality: ["smart", "tidy", "cheerful", "reliable"],
    favoriteItem: "notebook",
    favoriteFood: "rice ball",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["麻美吉准备好了。", "要把今天安排得闪闪发亮。"],
    voiceLine: "ready-plan",
    theme: { primary: "#fff7d6", secondary: "#e9be3f", accent: "#5d4610" },
    ready: true
  },
  {
    id: "meowtchi",
    name: "猫猫吉",
    member: "Tamagotchi Land",
    animalType: "cat mascot",
    personality: ["nimble", "cozy", "curious", "sweet"],
    favoriteItem: "yarn ball",
    favoriteFood: "fish cookie",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["猫猫吉打了个小盹。", "喵，桌面巡视中。"],
    voiceLine: "meow-patrol",
    theme: { primary: "#eef6ff", secondary: "#85bce8", accent: "#254e73" },
    ready: true
  },
  {
    id: "mimitchi",
    name: "咪咪吉",
    member: "Tamagotchi Land",
    animalType: "bunny mascot",
    personality: ["polite", "quick", "bright", "gentle"],
    favoriteItem: "mini ribbon",
    favoriteFood: "carrot tart",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["咪咪吉竖起耳朵。", "听见开心的声音了。"],
    voiceLine: "bunny-listen",
    theme: { primary: "#f4f0ff", secondary: "#b99ce8", accent: "#46326e" },
    ready: true
  },
  {
    id: "molmotchi",
    name: "摩尔吉",
    member: "Tamagotchi Land",
    animalType: "guinea pig mascot",
    personality: ["round", "cozy", "patient", "hungry"],
    favoriteItem: "leaf blanket",
    favoriteFood: "lettuce roll",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["摩尔吉在咕噜咕噜。", "可以加餐吗？"],
    voiceLine: "snack-please",
    theme: { primary: "#eff8e9", secondary: "#a9cc75", accent: "#415b24" },
    ready: true
  },
  {
    id: "pochi",
    name: "波吉",
    member: "Tamagotchi Land",
    animalType: "puppy mascot",
    personality: ["loyal", "bouncy", "friendly", "eager"],
    favoriteItem: "tiny ball",
    favoriteFood: "bone biscuit",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["波吉等你一起玩。", "尾巴正在高速运转。"],
    voiceLine: "puppy-play",
    theme: { primary: "#fff3e5", secondary: "#e59c4d", accent: "#673711" },
    ready: true
  },
  {
    id: "potsunentchi",
    name: "一朵吉",
    member: "Tamagotchi Land",
    animalType: "tiny sprout mascot",
    personality: ["quiet", "soft", "hopeful", "steady"],
    favoriteItem: "rain drop",
    favoriteFood: "sun candy",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["一朵吉冒出来了。", "慢慢长大也很好。"],
    voiceLine: "sprout-rise",
    theme: { primary: "#eaf8f4", secondary: "#71c6b0", accent: "#1f5f50" },
    ready: true
  },
  {
    id: "ratchi",
    name: "乐乐吉",
    member: "Tamagotchi Land",
    animalType: "rat mascot",
    personality: ["merry", "busy", "clever", "tiny"],
    favoriteItem: "little coin",
    favoriteFood: "cheese puff",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["乐乐吉找到好东西。", "快乐可以很小一颗。"],
    voiceLine: "lucky-find",
    theme: { primary: "#f1f1f1", secondary: "#a9adb4", accent: "#3e444d" },
    ready: true
  },
  {
    id: "reopacchi",
    name: "守宫吉",
    member: "Tamagotchi Land",
    animalType: "gecko mascot",
    personality: ["watchful", "mellow", "sticky", "brave"],
    favoriteItem: "wall sticker",
    favoriteFood: "fruit jelly",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["守宫吉贴在桌边。", "这里由我守护。"],
    voiceLine: "gecko-guard",
    theme: { primary: "#eef4ff", secondary: "#7d9fe5", accent: "#263f75" },
    ready: true
  },
  {
    id: "sebiretchi",
    name: "龙崽吉",
    member: "Tamagotchi Land",
    animalType: "dragon mascot",
    personality: ["proud", "tiny", "warm", "brave"],
    favoriteItem: "shiny scale",
    favoriteFood: "spicy cracker",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["龙崽吉练习喷小火。", "今天的勇气有一点烫。"],
    voiceLine: "dragon-spark",
    theme: { primary: "#fff0ed", secondary: "#e7785f", accent: "#702719" },
    ready: true
  },
  {
    id: "shigemi-san",
    name: "灌木吉",
    member: "Tamagotchi Land",
    animalType: "shrub mascot",
    personality: ["mysterious", "green", "patient", "kind"],
    favoriteItem: "garden tag",
    favoriteFood: "morning dew",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["灌木吉沙沙作响。", "路过的人都会变幸运。"],
    voiceLine: "leaf-rustle",
    theme: { primary: "#edf7dc", secondary: "#82b95a", accent: "#2d5523" },
    ready: true
  },
  {
    id: "shiipucchi",
    name: "咩咩吉",
    member: "Tamagotchi Land",
    animalType: "sheep mascot",
    personality: ["fluffy", "gentle", "sleepy", "sweet"],
    favoriteItem: "cloud pillow",
    favoriteFood: "milk pudding",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["咩咩吉数到一就困了。", "云朵一样轻轻待着。"],
    voiceLine: "sheep-cloud",
    theme: { primary: "#fffdf5", secondary: "#d8c989", accent: "#5a5130" },
    ready: true
  },
  {
    id: "tustustchi",
    name: "刺刺吉",
    member: "Tamagotchi Land",
    animalType: "spiky mascot",
    personality: ["spunky", "careful", "honest", "small"],
    favoriteItem: "safety glove",
    favoriteFood: "crunchy seed",
    visualStyle: "2D chibi Tamagotchi land desktop pet.",
    bubbleText: ["刺刺吉其实很温柔。", "靠近前先打个招呼。"],
    voiceLine: "spike-soft",
    theme: { primary: "#f5efe7", secondary: "#b98558", accent: "#56351f" },
    ready: true
  }
];

const LAND_ANIMATIONS = {
  idle: "Soft blink and breathing loop.",
  "running-right": "Tiny rightward trot.",
  "running-left": "Tiny leftward trot.",
  waving: "Small friendly wave.",
  jumping: "Short happy hop.",
  failed: "A brief discouraged beat.",
  waiting: "Quiet waiting sway.",
  running: "Busy little work loop.",
  review: "Focused inspection pose."
};

LAND_PETS.forEach((pet) => {
  pet.animations = { ...LAND_ANIMATIONS };
});

window.LAND_PETS = LAND_PETS;
window.BND_PETS = LAND_PETS;
